### ISSUE TITLE
How to compile and use this on Windows

### ISSUE THREAD

**Issue by veso266** [ryedwards/budgetcan-fw#8]
Hi there, I was hapily playing with 500kbps CAN on my MCP2515 breakout board with arduino when in the middle the thing stopped receiving data, not sure what happened maybe my MCP2515 got friend, idk

since I don't have time to get another one to verify this (that I fried my MCP2515 not something on my CAN Network) , I searched for an alternative solution and remembered that I have one [STM32H750B-DK](https://www.st.com/en/evaluation-tools/stm32h750b-dk.html) laying around

I know the thing (STM32H750B-DK) has built in 2x CAN-FD transciever and found this FW

So whats the best and quickest way to compile this on windows (I do have STM32CubeIDE 1.4.0 installed, but didn't find any project for it here in this repo) just to see if STM32H750B-DK can receive my 500kbs can comunication then I fried my MCP2515 module

of course if you have any good CAN example for STM32H750B-DK that would also be great

Thanks for Anwsering and Best Regards

**Comment by ryedwards** [comment]
I use vscode for my IDE.  I'll try to do my best to explain my setup.  It's been a long time since I set up my system and I did it in steps as I converted from CubeIDE.

I will also commit my .vscode directory to make things easier.

In vscode I added the following extensions:
- C/C++
- C/C++ Extension Pack
- Cortex-Debug
- Makefile Tools

You need to download the ARM compiler (if not already part of your system)
https://developer.arm.com/downloads/-/gnu-rm

You will also need to download GNU tools to get "make"
https://gnuwin32.sourceforge.net/

If you want to debug you'll also need to download and install OpenOCD and add the binary directory to your PATH

I added the following to my Windows path which matches my config in my .vscode
- Name: ARMGCC
- Value: C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin
Replace the "10 1021.10" with the version that you install
I also added the directory to my system PATH.
You also need to add the GNU32 bin directory into your path if it isn't automatically done by the installer

If you've set everything up correctly you should be able to build any of the existing configs by hitting "ctrl+shift+b"

Let me know if the above works.
